- name: demo of vars
  hosts: localhost
  become: true
  vars:
    - URL_Play: play.example.com
    - Age: 18

  tasks:
    - name: Print Name
      ansible.builtin.debug:
        msg: URL Play is {{ URL_Play }} {{ Age }}
    - name: task variable
      ansible.builtin.debug:
        msg: URL Task is {{ URL_Task }} {{ Age }}
      vars:
        - URL_Task: Task level Variable
        - Age: 20
#    Store the results of a task to an output file
    - name: Demo of output file
      ansible.builtin.shell: uptime
      register: output

#      Retreive the output file
    - name: Print the output the file
      ansible.builtin.debug:
        msg: "{{ output }}"

#      Retreive the output file using JSON query
    - name: Print the output the previous WITHOUT shell command
      ansible.builtin.debug:
        msg: "{{ output.stdout }}"


  roles:
    - demo
#Play level variables cane be accessed by all the tasks and roles
#Task level can be accessed only at task level
#CLI variable is the highest priority
#Role level variables is accessible in the role>tasks

#Imp: if the value of any key is a variable then double quote it
#eg: msg: {{ URL }}... this needs to be given as "{{ URL }}" .
#  This is not required if the msg starts with a string and then you give a variable,
#           as done in this file above
