- name: Demo of template files
  hosts: localhost
  become: true
  tasks:
    - name: Copy example.config file
      ansible.builtin.copy:
        src: example.conf
        dest: /temp/example-copy.conf\

    - name: Template example.config file
      ansible.builtin.template:
        src: example.conf
        dest: /temp/example-template.conf