- name: Demo on Tags
  hosts: localhost
  tasks:
    - name: Print Vegetables
      ansible.builtin.debug:
        msg: Vegetables
      tags: Vegetables

    - name: Print fruits
      ansible.builtin.debug:
        msg: Fruits
      tags: Fruits